/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HBackTop: typeof import('./../src/components/ep-navigation/HBackTop.vue')['default']
    HCheckbox: typeof import('./../src/components/ep-form/components/HCheckbox.vue')['default']
    HCheckboxButton: typeof import('./../src/components/ep-form/components/HCheckboxButton.vue')['default']
    HCheckboxButtonSpacing: typeof import('./../src/components/ep-form/components/HCheckboxButtonSpacing.vue')['default']
    HForm: typeof import('./../src/components/ep-form/components/HForm.vue')['default']
    HFormItem: typeof import('./../src/components/ep-form/components/HFormItem.vue')['default']
    HInput: typeof import('./../src/components/ep-form/components/HInput.vue')['default']
    HRadio: typeof import('./../src/components/ep-form/components/HRadio.vue')['default']
    HRadioButton: typeof import('./../src/components/ep-form/components/HRadioButton.vue')['default']
    HRadioButtonSpacing: typeof import('./../src/components/ep-form/components/HRadioButtonSpacing.vue')['default']
    HSwitch: typeof import('./../src/components/ep-form/components/HSwitch.vue')['default']
    HTable: typeof import('./../src/components/ep-table/components/HTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestGlobal: typeof import('./../src/components/global/TestGlobal.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
